"""init tables

Revision ID: c5c251226e5e
Revises: 3aa29df1cb26
Create Date: 2025-08-17 13:33:51.382294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5c251226e5e'
down_revision: Union[str, Sequence[str], None] = '3aa29df1cb26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secret', sa.JSON(), nullable=False),
    sa.Column('attempts_used', sa.Integer(), nullable=True),
    sa.Column('history', sa.JSON(), nullable=True),
    sa.Column('won', sa.Boolean(), nullable=True),
    sa.Column('lost', sa.Boolean(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
